name: baby_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  image_path: "assets/iconoBabyApp.png"
  adaptive_icon_background: "#F7F5F2"
  adaptive_icon_foreground: "assets/iconoBabyApp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/iconoBabyApp.png

flutter_native_splash:
  color: "#F7F5F2"
  image: assets/iconoBabyApp.png

  android_12:
    color: "#F7F5F2"
    image: assets/iconoBabyApp.png